# Generated by Django 5.1.2 on 2025-04-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_monthsummary_joining_date_monthsummary_leaving_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthsummary',
            name='month',
            field=models.CharField(default='April', max_length=10),
        ),
    ]
